HAI 1.2

	I HAS A V1
	I HAS A V2
	I HAS A CHOICE
	PLZ OPEN FILE "banco.txt"?
		VISIBLE FILE
	VISIBLE "VALUE1"
	GIMMEH V1
	VISIBLE "VALUE2"
	GIMMEH V2VISIBLE "Choose Operation? + - * /"
	GIMMEH CHOICE CHOICE, WTF?


KTHXBYE